on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Java + Loom early access build
    steps:
      - uses: actions/checkout@v2
      - name: setup
        uses: sormuras/setup-jdk@main
        with:
          website: java.net
          feature: Loom
      - name: build
        run: |
          mvn -B package
