on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 7 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Java + Loom early access build
    steps:
      - uses: actions/checkout@v3
      - name: setup
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: 20
      - name: build
        run: |
          mvn -B package
